version: '3'

services:
    nodejs-app:
        build:
          context: ./src
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "8080:8080" 
        links:
            - redis
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net
    redis:
        image: redis:alpine
        container_name: cache
        ports:
            - '6379:6379'
        networks:
            - example-net


networks:
  example-net:
    driver: bridge
