version: '3'

services:
    nodejs-app:
        build:
          context: ./src
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "8080:8080" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
volumes:
    mongodb:

networks:
  example-net:
    driver: bridge
