version: '3'

services:
    nodejs-app:
        build:
          context: ./src
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "8080:8080" 
        links:
            - mongo
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net
        labels:
            kompose.service.type: LoadBalancer
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '2701:2701'
        networks:
            - example-net
volumes:
    mongodb:

networks:
  example-net:
    driver: bridge
